# Generated by Django 3.2.10 on 2023-04-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campus', models.CharField(max_length=200)),
                ('sigla_campus', models.CharField(max_length=50)),
                ('status_campus', models.BooleanField(choices=[(True, 'Ativado'), (False, 'Desativado')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelCursoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_nivelcurso', models.CharField(max_length=200)),
                ('descricao_nivelcurso', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CursosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=200)),
                ('apelido_curso', models.CharField(max_length=200)),
                ('ead_curso', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('descritivo_curso', models.CharField(max_length=600)),
                ('area_atuacao_curso', models.CharField(max_length=600)),
                ('pre_requisito_curso', models.CharField(max_length=600)),
                ('campus_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_curso', to='guia_cursos.campusmodel')),
                ('nivel_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivelcurso_curso', to='guia_cursos.nivelcursomodel')),
            ],
        ),
    ]
