# Generated by Django 3.2.10 on 2024-08-19 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocore.apps.login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_foto', models.ImageField(blank=True, default='imagens/user.png', upload_to=djangocore.apps.login.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
